version: "3.8"

networks:
  elk:

services:
  elasticsearch:
    image: elasticsearch:7.12.0
    container_name: elasticsearch
    user: root
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      ELASTIC_PASSWORD: mostafa@123456
      discovery.type: single-node
    volumes:
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
#      - "/mnt/elasticsearch/data:/usr/share/elasticsearch/data"
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          memory: 6G
    networks:
      - elk
# why 4g ram?
  logstash:
    image: logstash:7.12.0
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xms1g -Xmx1g"
   # configs:
   #   - source: logstash_pipeline
   #     target: /usr/share/logstash/pipeline/logstash.conf
     # - source: logstash_config
     #   target: /usr/share/logstash/config/logstash.yml
    volumes:
      - "./logstash.yml:/usr/share/logstash/config/logstash.yml"
      - "./logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          memory: 6G
    networks:
      - elk

  journalbeat:
    image: docker.elastic.co/beats/journalbeat:7.12.0
    container_name: journalbeat
    user: root
    volumes:
      - "/var/log/journal:/var/log/journal"
      - "/etc/machine-id:/etc/machine-id"
      - "/run/systemd:/run/systemd"
      - "/etc/hostname:/etc/hostname:ro"
      - "./journalbeat.yml:/usr/share/journalbeat/journalbeat.yml"
      - "./config:/config"
    deploy:
      mode: global
    logging:
      driver: "journald"
    networks:
      - elk

  kibana:
    image: kibana:7.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    volumes:
      - "./kibana.yml:/usr/share/kibana/config/kibana.yml"
    logging:
      driver: "journald"
    networks:
      - elk

